name: Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up MSVC 2019
      uses: ilammy/msvc-dev-cmd@v1

    - name: Download yaqti Release
      run: |
          Invoke-WebRequest https://github.com/global667/yaqti/releases/download/v1/yaqti-main.zip -OutFile ./yaqti.zip     
    
    - name: Extract yaqti Release
      run: |
          Expand-Archive yaqti.zip

    - name: Install Qt using yaqti
      run: |
          cd yaqti
          cd yaqti-main
          cd yaqti
          python -m yaqti install --os windows --platform desktop --version 6.7.0 --modules qt.qt6.670.win64_msvc2019_64 

    #- name: Build and Test
    #  run: |
          # Add commands to build and test your project here
     #     echo "Build and test commands go here"


    #- uses: global667/yaqti@v1
    #  with:
    #        version: '6.2.0'
    #        os: 'windows'
    #        platform: 'desktop'
    #        modules: 'qt.qt6.620.win64_msvc2019_64'

    - name: Build Project
      run: |
        cd $GITHUB_REPOSITORY 
        mkdir build
        cd build
        cmake --build . --config Release

#    - name: Run tests
#      run: |
#        cd build
#        ctest -C Release




